apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.vanniktech.maven.publish'
apply plugin: 'org.jetbrains.dokka'
apply plugin: 'com.github.gmazzo.buildconfig'

dependencies {
  compileOnly gradleApi()
  compileOnly libs.kotlin.gradlePlugin

  testImplementation libs.junit
  testImplementation libs.assertk
  testImplementation libs.testParameterInjector
  testImplementation gradleTestKit()
}

gradlePlugin {
  plugins {
    confundus {
      id = "com.jakewharton.confundus"
      displayName = "unsafeCast for Kotlin/JVM"
      description = "A port of Kotlin/JS's unsafeCast for Kotlin/JVM"
      implementationClass = "com.jakewharton.confundus.gradle.ConfundusPlugin"
    }
  }
}

test {
  dependsOn(':confundus-api:publishAllPublicationsToTestMavenRepository')
  dependsOn(':confundus-compiler:publishAllPublicationsToTestMavenRepository')
  dependsOn(':confundus-gradle:publishAllPublicationsToTestMavenRepository')
}

// HEY! If you update the minimum-supported Gradle version check to see if the Kotlin language version or
// Java targets below can be bumped. See https://docs.gradle.org/current/userguide/compatibility.html.
def minimumGradleVersion = '9.0'
configurations.apiElements {
  attributes {
    attribute(
      GradlePluginApiVersion.GRADLE_PLUGIN_API_VERSION_ATTRIBUTE,
      objects.named(GradlePluginApiVersion, minimumGradleVersion),
    )
  }
}

apply plugin: 'com.gradleup.tapmoc'
tapmoc {
  java(17)
  kotlin('2.2.0')
}

buildConfig {
  useKotlinOutput {
    packageName = 'com.jakewharton.confundus.gradle'
    internalVisibility = true
    topLevelConstants = true
  }

  buildConfigField("String", "ConfundusVersion", "\"$version\"")

  sourceSets.getByName('test') {
    buildConfigField(String, 'MINIMUM_GRADLE_VERSION', minimumGradleVersion)
  }
}
