import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

buildscript {
  dependencies {
    classpath libs.kotlin.gradlePlugin
    classpath "com.jakewharton.confundus:confundus-gradle:${confundusVersion}"
  }
  repositories {
    maven {
      url "file://${projectDir.absolutePath}/../../../../../build/testMaven"
    }
    mavenCentral()
  }
}

apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'com.jakewharton.confundus'

repositories {
  maven {
    url "file://${projectDir.absolutePath}/../../../../../build/testMaven"
  }
  mavenCentral()
}

tasks.withType(JavaCompile).configureEach { task ->
  task.sourceCompatibility = '1.8'
  task.targetCompatibility = '1.8'
}

tasks.withType(KotlinJvmCompile).configureEach { task ->
  task.compilerOptions {
    jvmTarget = JvmTarget.JVM_1_8
  }
}
