import tapmoc.Severity

buildscript {
  dependencies {
    classpath libs.kotlin.gradlePlugin
    classpath libs.gradleMavenPublishPlugin
    classpath libs.dokkaPlugin
    classpath libs.buildConfigPlugin
    classpath libs.compatPlugin
  }

  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}

subprojects {
  group = GROUP
  version = VERSION_NAME

  repositories {
    mavenCentral()
  }

  tasks.withType(Test).configureEach {
    testLogging {
      if (System.getenv("CI") == "true") {
        events = ["failed", "skipped", "passed"]
      }
      exceptionFormat "full"
    }
  }

  plugins.withId('com.gradleup.tapmoc') {
    tapmoc {
      checkApiDependencies(Severity.ERROR)
      checkRuntimeDependencies(Severity.ERROR)
    }
  }

  plugins.withId('maven-publish') {
    publishing {
      repositories {
        maven {
          name = "TestMaven"
          url = file("${rootProject.buildDir}/testMaven").toURI().toString()
        }
      }
    }
  }
}
