import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

buildscript {
  dependencies {
    classpath libs.kotlin.gradlePlugin
    classpath libs.gradleMavenPublishPlugin
    classpath libs.dokkaPlugin
    classpath libs.buildConfigPlugin
  }

  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}

subprojects {
  group = GROUP
  version = VERSION_NAME

  repositories {
    mavenCentral()
  }

  tasks.withType(JavaCompile).configureEach { task ->
    task.sourceCompatibility = '1.8'
    task.targetCompatibility = '1.8'
  }

  tasks.withType(KotlinJvmCompile).configureEach { task ->
    task.compilerOptions {
      jvmTarget = JvmTarget.JVM_1_8
    }
  }

  plugins.withId('maven-publish') {
    publishing {
      repositories {
        maven {
          name = "TestMaven"
          url = file("${rootProject.buildDir}/testMaven").toURI().toString()
        }
      }
    }
  }
}
