apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'com.vanniktech.maven.publish'
apply plugin: 'org.jetbrains.dokka'

dependencies {
  compileOnly libs.kotlin.compiler

  testImplementation libs.kotlin.stdlib
  testImplementation libs.junit
  testImplementation libs.assertk
  testImplementation libs.kotlinCompilerTester
  testImplementation libs.asm.util
  testImplementation project(':confundus-api')
}

tasks.named('dokkaHtml').configure {
  it.dependsOn(tasks.named('kaptKotlin'))
}

apply plugin: 'com.gradleup.tapmoc'
tapmoc {
  java(8)
  kotlin('2.3.0')
}
